export const products = [
    {
      id: 1,
      name: 'Odonil',
      imageUrl: './images/odonel.jpg',
      description: 'This is a great product.',
      price: '₹40.00',
    },
    {
      id: 2,
      name: 'Genda',
      imageUrl: './images/ganda.jpg',
      description: 'This is another great product.',
      price: '₹100.00',
    },
    {
      id: 3,
      name: 'room',
      imageUrl: './images/room.jpg',
      description: 'This is another best one product.',
      price: '₹150.00',
    },
    {
        id: 4,
        name: 'A4 PAPER',
        imageUrl: './images/paper.jpg',
        description: 'This is another great product.',
        price: '210.00',
      },
      {
        id: 5,
        name: 'Product 3x',
        imageUrl: './images/6.JPG',
        description: 'This is another great product.',
        price: '$20.00',
      },
      {
        id: 6,
        name: 'harpik',
        imageUrl: './images/harpik.jpg',
        description: 'This is best product.',
        price: '45.00',
      },
    {
        id: 7,
        name: 'Product 3x',
        imageUrl: './images/8.jpg',
        description: 'This is another great product.',
        price: '$20.00',
      },
    {
        id: 8,
        name: 'Product 3x',
        imageUrl: './images/8.jpg',
        description: 'This is another great product.',
        price: '$20.00',
      },
    {
        id: 9,
        name: 'Product 3x',
        imageUrl: './images/8.jpg',
        description: 'This is another great product.',
        price: '$20.00',
      },
    {
        id: 10,
        name: 'Product 3x',
        imageUrl: './images/8.jpg',
        description: 'This is another great product.',
        price: '$20.00',
      },
    {
        id: 11,
        name: 'Product 3x',
        imageUrl: './images/8.jpg',
        description: 'This is another great product.',
        price: '$20.00',
      },
    {
        id: 12,
        name: 'Product 3x',
        imageUrl: './images/8.jpg',
        description: 'This is another great product.',
        price: '$20.00',
      },
  ];
