export const products = [
    {
      id: 1,
      name: 'Odonil',
      imageUrl: './images/odonel.jpg',
      description: 'This is a great product.',
      price: '₹40.00',
    },
    {
      id: 2,
      name: 'Genda',
      imageUrl: './images/ganda.jpg',
      description: 'This is another great product.',
      price: '₹100.00',
    },
    {
      id: 3,
      name: 'room',
      imageUrl: './images/room.jpg',
      description: 'This is another best one product.',
      price: '₹150.00',
    },
    {
        id: 4,
        name: 'PAPER A4',
        imageUrl: './images/A4paper.jpg',
        description: 'This is one product.',
        price: '210.00',
      },
      {
        id: 5,
        name: 'COLIN',
        imageUrl: './images/colin.jpg',
        description: 'This is another great product.',
        price: '45.00',
      },
      {
        id: 6,
        name: 'harpik',
        imageUrl: './images/harpik.jpg',
        description: 'This is best product.',
        price: '45.00',
      },
    {
        id: 7,
        name: 'AIR POCKET',
        imageUrl: './images/AIRPOCKET.jpg',
        description: 'FOR TOILET & FOUR WEHILER.',
        price: '60.00',
      },
    {
        id: 8,
        name: 'BOROSIL GLASS 6PC SET',
        imageUrl: './images/BOROSIL.jpg',
        description: 'This use in office & home product.',
        price: '500.00',
      },
    {
        id: 9,
        name: 'Product 3x',
        imageUrl: './images/8.jpg',
        description: 'This is another great product.',
        price: '$20.00',
      },
    {
        id: 10,
        name: 'Product 3x',
        imageUrl: './images/8.jpg',
        description: 'This is another great product.',
        price: '$20.00',
      },
    {
        id: 11,
        name: 'Product 3x',
        imageUrl: './images/8.jpg',
        description: 'This is another great product.',
        price: '$20.00',
      },
    {
        id: 12,
        name: 'Product 3x',
        imageUrl: './images/8.jpg',
        description: 'This is another great product.',
        price: '$20.00',
      },
  ];
