name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - master      # Change this to 'master' or your default branch if different
    paths:
      - 'src/**'  # Trigger on any change in the 'src' folder

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Configure Git
      run: |
        git config --global user.email "mohit3wadhwa@gmail.com"
        git config --global user.name "mohit3wadhwa"

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        npm run deploy
