name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - master      # Change this to 'master' or your default branch if different
    paths:
      - 'src/**'  # Trigger on any change in the 'src' folder

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use the version of Node you prefer

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: gdggd
      run: npm install -g gh-pages --save-dev

    - name: Deploy to GitHub Pages
      run: npm run deploy
      env:
        CI: false
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
